// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbt9WFfgS_5FBMbADTJrJCiwXlrAiQphg',
    appId: '1:715801902844:ios:f740274a167f7af07a6179',
    messagingSenderId: '715801902844',
    projectId: 'tabs-app-32dc9',
    storageBucket: 'tabs-app-32dc9.firebasestorage.app',
    iosClientId: '715801902844-2v53aov2f8ejc9f0qnvsd2p0vb7jtqr5.apps.googleusercontent.com',
    iosBundleId: 'com.tabs.tabs',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZ6hYjoWlNOve5yfSrY3wyDMRTKduGck',
    appId: '1:715801902844:web:d938daa67b14ab917a6179',
    messagingSenderId: '715801902844',
    projectId: 'tabs-app-32dc9',
    authDomain: 'tabs-app-32dc9.firebaseapp.com',
    storageBucket: 'tabs-app-32dc9.firebasestorage.app',
    measurementId: 'G-JJYZ0YQWN8',
  );

}