// PLACEHOLDER - This file will be auto-generated by FlutterFire CLI
// Run: flutterfire configure --project=YOUR_PROJECT_ID
//
// After running the command, this file will be replaced with proper configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace with actual Firebase configuration
    // Run: flutterfire configure --project=YOUR_PROJECT_ID
    throw UnsupportedError(
      'Firebase has not been configured for this project. '
      'Run "flutterfire configure" to generate firebase_options.dart',
    );
  }
}
